### ISSUE TITLE
Show the exact line where exception happened.

### ISSUE THREAD

**Issue by xeioex** [nginx/njs#140]
Currently only function level stack trace is available.

trace.js
```js
function f() {
    var a
    var b

    return ({}).a.a;
} 

f();
```

```
njs test.js
TypeError: cannot get property "a" of undefined
    at f (trace.js:2)
    at main (native)

```

correct line is: 5

**Comment by xeioex** [comment]
@drsm, @hongzhidao  Welcome to test https://gist.github.com/bca1263094b3b0b48e8f20236fc079c1

**Comment by hongzhidao** [comment]
@xeioex 

Works well. And the implementation is very concise.
BTW, I will be affected a litter by [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), and you introduced the thing `line number`.

1. rename `njs_generate_map` as `njs_generate_code_map`.
Since `njs_generate_map` may be introduced in the future for `Map` object.

2. go further
```
typedef struct {
    uint32_t                 offset;
    uint32_t                 line;
} njs_vm_line_num_t;


typedef struct {
    u_char                   *start;
    u_char                   *end;
    njs_str_t                file;
    njs_str_t                name;
    njs_arr_t                *lines;  /* of njs_vm_line_num_t */
} njs_vm_code_t;
```

**Comment by drsm** [comment]
a template literal may cause wrong line numbers:

```js
$ cat lines.js 

var lines1 = `
var a = 1;
var b = 2;
if (test) {
throw new Error('one');
} else {
throw new Error('two');
}
`;

var lines2 = "\n" +
"var a = 1;\n" +
"var b = 2;\n" +
"if (test) {\n" +
"throw new Error('one');\n" +
"} else {\n" +
"throw new Error('two');\n" +
"}\n";

var lines = process.argv[2] ? lines1 : lines2;

try {
    var f = new Function('test', 'line', lines);
    f(true);
} catch (e) {
    console.log(e);
}

try {
    var f = new Function('test', lines);
    f(false);
} catch (e) {
    console.log(e);
}

console.log(lines1 == lines2, lines1.length, lines2.length);
$ build/njs lines.js 
Error: one
    at anonymous (runtime:5)
    at main (lines.js:18)

Error: two
    at anonymous (runtime:7)
    at main (lines.js:25)

false 93 94
undefined
$ build/njs lines.js 1
Error: one
    at anonymous (runtime:4)
    at main (lines.js:18)

Error: two
    at anonymous (runtime:6)
    at main (lines.js:25)

false 93 94
undefined
$ node lines.js 
Error: one
    at eval (eval at <anonymous> (/home/drsm/work/njs/lines.js:24:13), <anonymous>:5:7)
    at Object.<anonymous> (/home/drsm/work/njs/lines.js:25:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Error: two
    at eval (eval at <anonymous> (/home/drsm/work/njs/lines.js:31:13), <anonymous>:7:7)
    at Object.<anonymous> (/home/drsm/work/njs/lines.js:32:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
true 94 94
$ node lines.js 1
Error: one
    at eval (eval at <anonymous> (/home/drsm/work/njs/lines.js:24:13), <anonymous>:5:7)
    at Object.<anonymous> (/home/drsm/work/njs/lines.js:25:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Error: two
    at eval (eval at <anonymous> (/home/drsm/work/njs/lines.js:31:13), <anonymous>:7:7)
    at Object.<anonymous> (/home/drsm/work/njs/lines.js:32:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
true 94 94
```
