### ISSUE TITLE
parser segfault.

### ISSUE THREAD

**Issue by xeioex** [nginx/njs#147]
```sh
> cat njs.js
(0
--
>gdb --args njs njs.js
(gdb) r
Program received signal SIGSEGV, Segmentation fault.
0x0000000000406c65 in nxt_vsprintf (buf=0x7fffffffa9a2 "\377\377\377\177", end=0x7fffffffb190 "", fmt=0x462abb "\"", 
    args=0x7fffffffb1d0) at nxt/nxt_sprintf.c:135
135                     length = v->length;
(gdb) bt
#0  0x0000000000406c65 in nxt_vsprintf (buf=0x7fffffffa9a2 "\377\377\377\177", end=0x7fffffffb190 "", fmt=0x462abb "\"", 
    args=0x7fffffffb1d0) at nxt/nxt_sprintf.c:135
#1  0x000000000043e17c in njs_parser_scope_error (vm=0x681110, scope=0x688700, type=NJS_OBJECT_SYNTAX_ERROR, line=2, 
    fmt=0x462aa7 "Unexpected token \"%V\"", args=0x7fffffffb1d0) at njs/njs_parser.c:2378
#2  0x000000000043e3ae in njs_parser_lexer_error (vm=0x681110, parser=0x68b8c0, type=NJS_OBJECT_SYNTAX_ERROR, 
    fmt=0x462aa7 "Unexpected token \"%V\"") at njs/njs_parser.c:2408
#3  0x000000000043df4c in njs_parser_unexpected_token (vm=0x681110, parser=0x68b8c0, token=NJS_TOKEN_SEMICOLON)
    at njs/njs_parser.c:2313
#4  0x000000000043e6b9 in njs_parser_match (match=NJS_TOKEN_CLOSE_PARENTHESIS, token=NJS_TOKEN_SEMICOLON, parser=0x68b8c0, 
    vm=0x681110) at njs/njs_parser.h:198
#5  njs_parser_terminal (vm=0x681110, parser=0x68b8c0, token=NJS_TOKEN_SEMICOLON) at njs/njs_parser_terminal.c:61
#6  0x000000000044226d in njs_parser_call_expression (vm=0x681110, parser=0x68b8c0, token=NJS_TOKEN_OPEN_PARENTHESIS)
    at njs/njs_parser_expression.c:743
#7  0x0000000000442003 in njs_parser_post_inc_dec_expression (vm=0x681110, parser=0x68b8c0, token=NJS_TOKEN_OPEN_PARENTHESIS)
    at njs/njs_parser_expression.c:688
```

**Comment by hongzhidao** [comment]
@xeioex 

1. Fixed patch.
```
# HG changeset patch
# User hongzhidao <hongzhidao@gmail.com>
# Date 1556327064 -28800
# Node ID e80b991be074f1026f2dc3dd4249aeb0b0e9f71c
# Parent  60e98e247a5311e83aee15fd1ef7bc8ff9e8ee62
Improved njs_lexer_rollback().

diff -r 60e98e247a53 -r e80b991be074 njs/njs_lexer.c
--- a/njs/njs_lexer.c	Fri Apr 26 19:30:43 2019 +0300
+++ b/njs/njs_lexer.c	Sat Apr 27 09:04:24 2019 +0800
@@ -307,11 +307,6 @@ njs_lexer_token(njs_vm_t *vm, njs_lexer_

     lexer->prev_start = lexer->start;

-    if (lexer->lexer_token != NULL) {
-        lexer->prev_token = lexer->lexer_token->token;
-        nxt_mp_free(vm->mem_pool, lexer->lexer_token);
-    }
-
     if (nxt_queue_is_empty(&lexer->preread)) {
         lt = njs_lexer_token_push(vm, lexer);
         if (nxt_slow_path(lt == NULL)) {
@@ -319,7 +314,14 @@ njs_lexer_token(njs_vm_t *vm, njs_lexer_
         }
     }

-    lexer->lexer_token = njs_lexer_token_pop(lexer);
+    lt = njs_lexer_token_pop(lexer);
+
+    if (lexer->lexer_token != NULL && lexer->lexer_token != lt) {
+        lexer->prev_token = lexer->lexer_token->token;
+        nxt_mp_free(vm->mem_pool, lexer->lexer_token);
+    }
+
+    lexer->lexer_token = lt;

     return njs_lexer_token_name_resolve(lexer, lexer->lexer_token);
 }
diff -r 60e98e247a53 -r e80b991be074 njs/njs_lexer.h
--- a/njs/njs_lexer.h	Fri Apr 26 19:30:43 2019 +0300
+++ b/njs/njs_lexer.h	Sat Apr 27 09:04:24 2019 +0800
@@ -264,7 +264,6 @@ void njs_lexer_keyword(njs_lexer_t *lexe
 #define njs_lexer_rollback(lexer)                                              \
     do {                                                                       \
         nxt_queue_insert_head(&(lexer)->preread, &(lexer)->lexer_token->link); \
-        (lexer)->lexer_token = NULL;                                           \
     } while (0)


diff -r 60e98e247a53 -r e80b991be074 njs/test/njs_unit_test.c
--- a/njs/test/njs_unit_test.c	Fri Apr 26 19:30:43 2019 +0300
+++ b/njs/test/njs_unit_test.c	Sat Apr 27 09:04:24 2019 +0800
@@ -2157,6 +2157,12 @@ static njs_unit_test_t  njs_test[] =

     /* automatic semicolon insertion. */

+    { nxt_string("(a\n--"),
+      nxt_string("SyntaxError: Unexpected token \"--\" in 2") },
+
+    { nxt_string("(a\n++"),
+      nxt_string("SyntaxError: Unexpected token \"++\" in 2") },
+
     { nxt_string("var x = 0, y = 2; x\n--\ny; [x,y]"),
       nxt_string("0,1") },

```

2. How did you find this bug?

**Comment by xeioex** [comment]
@hongzhidao 
> How did you find this bug?

https://gist.github.com/xeioex/425583e7f37ee5ede094ffbe2c267eeb

**Comment by hongzhidao** [comment]
@xeioex 

```
diff -r 28c972d5416d njs/njs_function.c
--- a/njs/njs_function.c	Fri Apr 26 21:30:04 2019 +0800
+++ b/njs/njs_function.c	Sun Apr 28 00:13:08 2019 +0800
@@ -31,7 +31,6 @@ njs_function_alloc(njs_vm_t *vm, njs_fun
         goto fail;
     }

-
     /*
      * nxt_mp_zalloc() does also:
      *   nxt_lvlhsh_init(&function->object.hash);
```

**Comment by xeioex** [comment]
Fixed in https://github.com/nginx/njs/commit/3976d85373eb61eba14238bace4afe433ac7c208
