### ISSUE TITLE
Segfault in String.prototype.replace() with special chars in replace string.

### ISSUE THREAD

**Issue by xeioex** [nginx/njs#154]
```js
>  "o".replace("o\0")
=================================================================
==18056==ERROR: AddressSanitizer: negative-size-param: (size=-1)
    #0 0x7f1d206139a1 in __asan_memcpy (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x8c9a1)
    #1 0x433aa8 in njs_string_replace_join njs/njs_string.c:3540
    #2 0x432242 in njs_string_replace_search njs/njs_string.c:3261
    #3 0x430541 in njs_string_prototype_replace njs/njs_string.c:3029
    #4 0x45effd in njs_function_native_call njs/njs_function.c:587
    #5 0x41c6f7 in njs_vmcode_continuation njs/njs_vm.c:2294
    #6 0x413d4f in njs_vmcode_interpreter njs/njs_vm.c:159
    #7 0x412c24 in njs_vm_start njs/njs.c:594
    #8 0x4049e6 in njs_process_script njs/njs_shell.c:772
    #9 0x4037e2 in njs_interactive_shell njs/njs_shell.c:502
    #10 0x4029f1 in main njs/njs_shell.c:271
    #11 0x7f1d1fa1e82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

0x619000002bb4 is located 820 bytes inside of 1024-byte region [0x619000002880,0x619000002c80)
allocated by thread T0 here:
    #0 0x7f1d20620076 in __interceptor_posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99076)
    #1 0x4b5a88 in nxt_memalign nxt/nxt_malloc.c:26
    #2 0x41012b in njs_align njs/njs.c:41
    #3 0x40b5e9 in nxt_mp_alloc_large nxt/nxt_mp.c:594
    #4 0x40b40e in nxt_mp_align nxt/nxt_mp.c:353
    #5 0x411faf in njs_vm_init njs/njs.c:403
    #6 0x410a63 in njs_vm_create njs/njs.c:181
    #7 0x404141 in njs_create_vm njs/njs_shell.c:654
    #8 0x4036ad in njs_interactive_shell njs/
```

**Comment by lexborisov** [comment]
Hi @xeioex 

Please, try [this patch](https://gist.github.com/72eba1e4a8e5e21e7392bc123aa3459f) for solve the problem.

Thank you for the report!
