### ISSUE TITLE
Segfault in nxt_utf8_next nxt/nxt_utf8.h:44

### ISSUE THREAD

**Issue by wrauner** [nginx/njs#167]
Testcase:
```js
var v0=Date()
if(v0.toBytes(v0.indexOf(),(100|(0)),(RegExp(((String()+(Boolean))+(v0))+v0.toUpperCase((ReferenceError()>0)))))){}
```

njs version:
`changeset:   965:e0fdef4eb478`

Stack trace (from ASAN):
```
==26742==ERROR: AddressSanitizer: SEGV on unknown address 0x62505a5ae62a (pc 0x559dc4b57d0c bp 0x625000008bf7 sp 0x7fff1a0b64b0 T0)
==26742==The signal is caused by a READ memory access.
    #0 0x559dc4b57d0b in nxt_utf8_next nxt/nxt_utf8.h:44
    #1 0x559dc4b57d0b in njs_string_offset njs/njs_string.c:2073
    #2 0x559dc4b5eff1 in njs_string_prototype_to_bytes njs/njs_string.c:1047
    #3 0x559dc4bfacdb in njs_function_native_call njs/njs_function.c:587
    #4 0x559dc4b22d82 in njs_vmcode_function_call njs/njs_vm.c:2061
    #5 0x559dc4b18d47 in njs_vmcode_interpreter njs/njs_vm.c:159
    #6 0x559dc4b13b83 in njs_vm_start njs/njs.c:594
    #7 0x559dc4af6cc3 in njs_process_script njs/njs_shell.c:770
    #8 0x559dc4aeff48 in njs_process_file njs/njs_shell.c:619
    #9 0x559dc4aeff48 in main njs/njs_shell.c:281
    #10 0x7fbdb7f77b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #11 0x559dc4af1ef9 in _start (/home/build/njs/build/njs+0x2aef9)
```
Found by [fluff](https://github.com/Samsung/Fluff)

**Comment by xeioex** [comment]
Looks like s a duplicate of #155
