### ISSUE TITLE
heap-buffer-overflow in njs_vm_value_dump njs/njs_json.c:2531

### ISSUE THREAD

**Issue by wrauner** [nginx/njs#196]
REPL session with ASAN:
```
interactive njs 0.3.4

v.<Tab> -> the properties and prototype methods of v.
type console.help() for more information

>> Object.values(njs)
[
 [Unknown value type:190]
]
>> Object.values(njs)
[
 [Unknown value type:208]
]
>> Object.values(njs)
=================================================================
==351==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6250000118f0 at pc 0x55f9891c035c bp 0x7ffc393b5990 sp 0x7ffc393b5980
READ of size 1 at 0x6250000118f0 thread T0
    #0 0x55f9891c035b in njs_vm_value_dump njs/njs_json.c:2531
    #1 0x55f989184fdf in njs_vm_retval_dump njs/njs.c:1022
    #2 0x55f9891792f8 in njs_output njs/njs_shell.c:708
    #3 0x55f9891795c0 in njs_process_script njs/njs_shell.c:774
    #4 0x55f98917a743 in njs_interactive_shell njs/njs_shell.c:501
    #5 0x55f98917a743 in main njs/njs_shell.c:271
    #6 0x7f65548e8b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #7 0x55f989177409 in _start (/home/Work/tools/njs/build/njs+0x27409)
```

**Comment by xeioex** [comment]
Fixed by https://github.com/nginx/njs/commit/f7f0adae0e48dd2007bb562dfa39295e282756a0
