### ISSUE TITLE
js exception is not logged on promise context

### ISSUE THREAD

**Issue by fernandoney** [nginx/njs#346]
```
$ nginx -V
nginx version: nginx/1.19.2
built by clang 10.0.1 (clang-1001.0.46.4)
built with OpenSSL 1.1.1g  21 Apr 2020 (running with OpenSSL 1.1.1h  22 Sep 2020)
TLS SNI support enabled
configure arguments: --prefix=/usr/local/Cellar/nginx-full/1.19.2 --with-http_ssl_module --with-pcre --with-ipv6 --sbin-path=/usr/local/Cellar/nginx-full/1.19.2/bin/nginx --with-cc-opt='-I/usr/local/include -I/usr/local/opt/pcre/include -I/usr/local/opt/openssl@1.1/include' --with-ld-opt='-L/usr/local/lib -L/usr/local/opt/pcre/lib -L/usr/local/opt/openssl@1.1/lib' --conf-path=/usr/local/etc/nginx/nginx.conf --pid-path=/usr/local/var/run/nginx.pid --lock-path=/usr/local/var/run/nginx.lock --http-client-body-temp-path=/usr/local/var/run/nginx/client_body_temp --http-proxy-temp-path=/usr/local/var/run/nginx/proxy_temp --http-fastcgi-temp-path=/usr/local/var/run/nginx/fastcgi_temp --http-uwsgi-temp-path=/usr/local/var/run/nginx/uwsgi_temp --http-scgi-temp-path=/usr/local/var/run/nginx/scgi_temp --http-log-path=/usr/local/var/log/nginx/access.log --error-log-path=/usr/local/var/log/nginx/error.log --with-http_auth_request_module --add-module=/usr/local/share/ngx-devel-kit --add-module=/usr/local/share/lua-nginx-module --add-module=/usr/local/share/njs-nginx-module/nginx
```

`nginx.conf`
```
worker_processes 1;

events {
   worker_connections 1024;
}

http {
   js_import /etc/nginx/js_error.js;

    server {
      listen 8888;

      location = /httpstat {
         proxy_pass http://httpstat.us/200;
      }

      location /call_unexisting_function {
         js_content js_error.call_unexisting_function;
      }

      location /call_unexisting_function_in_promise_context { 
         js_content js_error.call_unexisting_function_in_promise_context;
      }
   }
}
```
`js_error.js`
```

function call_unexisting_function(request) {
  //call a not defined function: log a message in error log
  unexisting_function(); 
}
  
function call_unexisting_function_in_promise_context(request) {
  request
    .subrequest("/httpstat", {
      method: "GET",
    })
    .then((reply) => {
      //call a not defined function: handled in catch block
      unexisting_function();
    })
    .catch((error) => {
      request.error('catch block')
      //call a not defined function: nothing is logged
      unexisting_function();
    });
}

export default { call_unexisting_function, call_unexisting_function_in_promise_context };
```
JS exceptions are not logged in the context of a promise. Errors are handled by `catch` block, however if the error happens in `catch` block itself I was expecting a message in error log.

- `curl http://localhost:8888/call_unexisting_function`  show js exception in error log

```
21:06:16 [error] 3344#0: *36 js exception: ReferenceError: "unexisting_function" is not defined in js_error.js:4
    at call_unexisting_function (js_error.js:2)
    at main (native)
, client: 127.0.0.1, server: , request: "GET /call_unexisting_function HTTP/1.1", host: "localhost:8888"
```

- `curl http://localhost:8888/call_unexisting_function_in_promise_context` does NOT show js exception in error log
```
21:08:16 [error] 3344#0: *37 js: catch block
```

**Comment by hongzhidao** [comment]
@xeioex 
It seems njs should support `ngx.log`, and reimplement `r.log`.
`r.log` needs to show the context information of the `r` HTTP request.

**Comment by drsm** [comment]
@fernandoney 

Hi!
Actually, there is no unhandled exception here. Is is a unhandled promise rejection.
`try/catch` in toplevel `.catch` block may help.

**Comment by xeioex** [comment]
@drsm 

```sh
$ cat github346.js 
Promise.resolve()
.then(() => {
        nonexsisting()
})
.catch(()=>{
        nonexsisting()
})

$ node github346.js 
(node:1849) UnhandledPromiseRejectionWarning: ReferenceError: nonexsisting is not defined
    at Promise.resolve.then.catch (/home/xeioex/workspace/nginx/nginScript/njs/github346.js:6:2)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:1849) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1849) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

$ ./build/njs github346.js 
$ ../quickjs/qjs github346.js
```

It seems the spec does not require anything here, but we may improve the user experience somehow.
For example by closing the connection with 500 error and "unhandled promise rejection".

**Comment by drsm** [comment]
@xeioex 

The spec require to return `normal completion` by default https://tc39.es/ecma262/#sec-host-promise-rejection-tracker.

> For example by closing the connection with 500 error and "unhandled promise rejection".

Yes, this will help a lot.

**Comment by lexborisov** [comment]
The [patch](https://gist.github.com/lexborisov/60c7d8a5b2888caa03ad172f658c442d).

@drsm 
Artem, could you take a look at behavior of promises, please. Maybe I forgot something?

**Comment by drsm** [comment]
@lexborisov 

Why it collects 'em?
```js
$ build/njs 
interactive njs 0.5.0

v.<Tab> -> the properties and prototype methods of v.

>> Promise.resolve().then(() => { throw new Error("test UPR")})
Promise {
 
}
Thrown:
Error: test UPR
>> Promise.resolve().then(() => { throw new Error("test UPR")})
Promise {
 
}
Thrown:
Error: test UPR,Error: test UPR
>> Promise.resolve().then(() => { throw new Error("test UPR")})
Promise {
 
}
Thrown:
Error: test UPR,Error: test UPR,Error: test UPR
>>
```

I think we need a way to distinguish UPR from a basic unhandled exception.
Maybe a special Error subtype, just to provide a better diagnostics.
There is no way to catch these exceptions gracefully anyway.
```js
$ build/njs 
interactive njs 0.5.0

v.<Tab> -> the properties and prototype methods of v.

>> Promise.reject().then(() => {})
Promise {
 
}
Thrown:

```

Sometimes it doesn't report:
```js
$ build/njs 
interactive njs 0.5.0

v.<Tab> -> the properties and prototype methods of v.

>> Promise.reject(new Error('one'));
Promise {
 
}
>> new Promise((resolve, reject) => { reject() })
Promise {
 
}
>> Promise.reject(new Error('one')).then(() => console.log('123'))
Promise {
 
}
Thrown:
Error: one,,Error: one
```

**Comment by lexborisov** [comment]
> @lexborisov
> 
> Why it collects 'em?
> 

Bug.

> 
> I think we need a way to distinguish UPR from a basic unhandled exception.
> Maybe a special Error subtype, just to provide a better diagnostics.
> There is no way to catch these exceptions gracefully anyway.
> 
> ```js
> $ build/njs 
> interactive njs 0.5.0
> 
> v.<Tab> -> the properties and prototype methods of v.
> 
> >> Promise.reject().then(() => {})
> Promise {
>  
> }
> Thrown:
> ```

In this case, must explicitly show the `Thrown: undefined`.
V8 does not use special exceptions for this, I tend to do the same behavior.

> 
> Sometimes it doesn't report:
> 
> ```js
> $ build/njs 
> interactive njs 0.5.0
> 
> v.<Tab> -> the properties and prototype methods of v.
> 
> >> Promise.reject(new Error('one'));
> Promise {
>  
> }
> >> new Promise((resolve, reject) => { reject() })
> Promise {
>  
> }
> >> Promise.reject(new Error('one')).then(() => console.log('123'))
> Promise {
>  
> }
> Thrown:
> Error: one,,Error: one
> ```

It looks like the accumulator of the previous two bugs.

@drsm  thanks, like nothing critical.

**Comment by drsm** [comment]
@lexborisov Yeah, looks like it works! Thanks!

Should it throw twice in this case?

```js
$ build/njs 
interactive njs 0.5.0

v.<Tab> -> the properties and prototype methods of v.

>> var ctl, p = new Promise((resolve, reject) => { ctl = { resolve, reject}; });
undefined
>> var a = p.then(() => {});
undefined
>> var b = p.then(() => {});
undefined
>> ctl.reject(new Error("x2"))
undefined
Thrown:
Error: x2,Error: x2
>>
```

**Comment by drsm** [comment]
@lexborisov 

> V8 does not use special exceptions for this, I tend to do the same behavior.

The latest node CLI:
```js
root@node:~# node --unhandled-rejections=strict
Welcome to Node.js v15.0.1.
Type ".help" for more information.
> Promise.reject()
Promise { <rejected> undefined }
> node:internal/process/promises:199
        triggerUncaughtException(err, true /* fromPromise */);
        ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
root@node:~# node --unhandled-rejections=throw
Welcome to Node.js v15.0.1.
Type ".help" for more information.
> Promise.reject()
Promise { <rejected> undefined }
> node:internal/process/promises:218
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
root@node:~# node --unhandled-rejections=warn
Welcome to Node.js v15.0.1.
Type ".help" for more information.
> Promise.reject()
Promise { <rejected> undefined }
> (node:28548) UnhandledPromiseRejectionWarning: undefined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28548) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

> 
(To exit, press Ctrl+C again or Ctrl+D or type .exit)
> 
root@node:~#
```
Actually, there is no difference between `--unhandled-rejections=throw` and `--unhandled-rejections=strict` in our case, 'cause we don't have a [uncaughtException](https://nodejs.org/api/process.html#process_event_uncaughtexception) hook.

**Comment by drsm** [comment]
Looks like `HostPromiseRejectionTracker(p, "handle")` is useless.
I see no way how to trigger it without previous UPR:
```js
root@node:~# node --unhandled-rejections=warn
Welcome to Node.js v15.0.1.
Type ".help" for more information.
> var p = Promise.reject(); void setImmediate(() => { p.catch(() => {})});
undefined
> (node:28632) UnhandledPromiseRejectionWarning: undefined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28632) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)

> 
(To exit, press Ctrl+C again or Ctrl+D or type .exit)
> 
```

**Comment by lexborisov** [comment]
The patch has a test for this

> Looks like `HostPromiseRejectionTracker(p, "handle")` is useless.

```JS
Promise.reject("test").catch((x) => console.log('rejected', x));
```

**Comment by drsm** [comment]
The purpose of `rejectionHandled` is to diagnose this type of errors:
```js
process.on('rejectionHandled', () => console.log('Rejection handled'));
process.on('unhandledRejection', () => console.log('Unhandled rejection'));

const timeOut = (timeout) => new Promise((resolve, reject) => void setTimeout(resolve, timeout));

const createProcess = () => timeOut(1000).then(() => { throw new Error('Failed'); });
const handleErrors = (target) => timeOut(1000).then(() => {
    console.log('I am here to help');
    target.catch(() => { console.log('done'); });
});


async function main() {
    const process = createProcess();

    try {
        await handleErrors(process);
        // ...
        await process;

    } catch(e) {
        console.log('something goes wrong', e);
    }
}
```

**Comment by lexborisov** [comment]
@drsm 

Artem thanks for the help!
